#include "htmlexporter.h"
#include <qdir.h>
#include <qregularexpression.h>

bool HtmlExporter::saveLabReport(QString filePath, QString patientName, QString sampleID, QString encryptedDna)
{
    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return false;

    QTextStream out(&file);

    QString htmlContent = R"(
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bio-Gen Lab Report</title>
    <style>
        body { font-family: 'Segoe UI', sans-serif; background: #f0f2f5; display: flex; justify-content: center; min-height: 100vh; align-items: center; }
        .report { background: white; width: 600px; padding: 40px; border-radius: 10px; box-shadow: 0 5px 15px rgba(0,0,0,0.1); border-top: 6px solid #2980b9; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 1px solid #ddd; padding-bottom: 20px; }
        .header h1 { color: #2c3e50; margin: 0; }
        .field { margin-bottom: 20px; }
        .label { font-weight: bold; color: #7f8c8d; display: block; margin-bottom: 5px; }
        .value { font-size: 18px; color: #2c3e50; font-weight: 500; }
        .dna-box { background: #ecf0f1; padding: 15px; border-radius: 5px; font-family: monospace; color: #e74c3c; word-break: break-all; letter-spacing: 1px; }
        .footer { margin-top: 40px; font-size: 12px; color: #95a5a6; text-align: center; }
    </style>
</head>
<body>

<div class="report">
    <div class="header">
        <h1>BIO-GEN LABS</h1>
        <p>Genetic Sequence Analysis Report</p>
    </div>

    <div class="field">
        <span class="label">Patient Name:</span>
        <span class="value">)" + patientName + R"(</span>
    </div>

    <div class="field">
        <span class="label">Sample ID (Ref):</span>
        <span class="value" id="sampleId">)" + sampleID + R"(</span>
    </div>

    <div class="field">
        <span class="label">Sequencing Result (Raw DNA):</span>
        <div class="dna-box" id="encryptedData">)" + encryptedDna + R"(</div>
    </div>

    <div class="footer">
        Generated by CryptoDesk System. Only authorized software can interpret this result.
    </div>
</div>

</body>
</html>
    )";

    out << htmlContent;
    file.close();
    return true;
}

ReportData HtmlExporter::parseLabReport(QString filePath)
{
    ReportData result;
    result.isValid = false; // افتراض إن الملف مش سليم لحد ما نثبت العكس

    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return result; // نرجع فاضي لو الملف مفتحش

    QString htmlContent = file.readAll();
    file.close();

    // البحث عن البيانات
    QRegularExpression idRegex("id=\"sampleId\">([^<]+)</span>");
    QRegularExpression dnaRegex("id=\"encryptedData\">([^<]+)</div>");

    QRegularExpressionMatch idMatch = idRegex.match(htmlContent);
    QRegularExpressionMatch dnaMatch = dnaRegex.match(htmlContent);

    if (idMatch.hasMatch() && dnaMatch.hasMatch()) {
        result.sampleID = idMatch.captured(1).trimmed();
        result.encryptedData = dnaMatch.captured(1).trimmed();
        result.isValid = true; // تمام لقينا البيانات
    }

    return result;
}
